        self.block_nmae = tk.Label(self, height=4, width=70, bg='lightsteelblue', text="細項排名")
        self.item_name = tk.Label(self, height=2, width=10, bg='lightgray', text="項目")
        self.index_name = tk.Label(self, height=2, width=40, bg='lightgray', text="指標名稱")
        self.industry = tk.Label(self, height=2, width=10, bg='lightgray', text="產業")
        self.period = tk.Label(self, height=2, width=10, bg='lightgray', text="期間")

    # 左邊標題
        self.common_item = tk.Label(self, height=6, width=10, bg='silver', text="常見\n指標")
        self.financial_structure = tk.Label(self, height=3, width=10, bg='lightgray', text="財務\n結構")
        self.repay_capability = tk.Label(self, height=3, width=10, bg='silver', text="償還\n能力")
        self.operate_capability = tk.Label(self, height=6, width=10, bg='lightgray', text="經營\n能力")
        self.profit_capability = tk.Label(self, height=4, width=10, bg='silver', text="獲利\n能力")
        self.cashflow = tk.Label(self, height=5, width=10, bg='lightgray', text="現金\n流量")

    # 細項指標
        self.index1 = tk.Label(self, height=1, width=70, bg='LightSalmon', text="淨利率")
        self.index2 = tk.Label(self, height=1, width=70, bg='LightSalmon', text="毛利率")
        self.index3 = tk.Label(self, height=1, width=70, bg='LightSalmon', text="殖利率")
        self.index4 = tk.Label(self, height=1, width=70, bg='LightSalmon', text="股利發放穩定性")
        self.index5 = tk.Label(self, height=1, width=70, bg='LightSalmon', text="盈餘分配率")
        self.index6 = tk.Label(self, height=1, width=70, bg='LightSalmon', text="淨值比")
        self.index7 = tk.Label(self, height=1, width=70, bg='bisque', text="本益比")
        self.index8 = tk.Label(self, height=1, width=70, bg='bisque', text="負債占資產比率(%)")
        self.index9 = tk.Label(self, height=1, width=70, bg='bisque', text="長期資金站不動產廠房及設備比率(%)")
        self.index10 = tk.Label(self, height=1, width=70, bg='LightSalmon', text="流動比率(%)")
        self.index11 = tk.Label(self, height=1, width=70, bg='LightSalmon', text="速動比率(%)")
        self.index12 = tk.Label(self, height=1, width=70, bg='LightSalmon', text="利息保障倍數(%)")
        self.index13 = tk.Label(self, height=1, width=70, bg='bisque', text="應收款項週轉率(次)")
        self.index14 = tk.Label(self, height=1, width=70, bg='bisque', text="平均收現日數")
        self.index15 = tk.Label(self, height=1, width=70, bg='bisque', text="存貨週轉率(次)")
        self.index16 = tk.Label(self, height=1, width=70, bg='bisque', text="平均銷貨日數")
        self.index17 = tk.Label(self, height=1, width=70, bg='bisque', text="不動產廠房及設備週轉率(次)")
        self.index18 = tk.Label(self, height=1, width=70, bg='bisque', text="總資產週轉率(次)")
        self.index19 = tk.Label(self, height=1, width=70, bg='LightSalmon', text="資產報酬率(%)")
        self.index20 = tk.Label(self, height=1, width=70, bg='LightSalmon', text="權益報酬率(%)")
        self.index21 = tk.Label(self, height=1, width=70, bg='LightSalmon', text="稅前純益佔實收資本比率(%)")
        self.index22 = tk.Label(self, height=1, width=70, bg='LightSalmon', text="純益率(%)")
        self.index23 = tk.Label(self, height=1, width=70, bg='bisque', text="每股盈餘(元)")
        self.index24 = tk.Label(self, height=1, width=70, bg='bisque', text="現金流量比率(%)")
        self.index25 = tk.Label(self, height=1, width=70, bg='bisque', text="現金流量允當比率(%)")
        self.index26 = tk.Label(self, height=1, width=70, bg='bisque', text="現金再投資比率(%)")

    # 產業細項
        self.industry1 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="1/k")
        self.industry2 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="1/k")
        self.industry3 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="1/k")
        self.industry4 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="1/k")
        self.industry5 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="1/k")
        self.industry6 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="1/k")
        self.industry7 = tk.Label(self, height=1, width=10, bg='bisque', text="1/k")
        self.industry8 = tk.Label(self, height=1, width=10, bg='bisque', text="1/k")
        self.industry9 = tk.Label(self, height=1, width=10, bg='bisque', text="1/k")
        self.industry10 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="1/k")
        self.industry11 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="1/k")
        self.industry12 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="1/k")
        self.industry13 = tk.Label(self, height=1, width=10, bg='bisque', text="1/k")
        self.industry14 = tk.Label(self, height=1, width=10, bg='bisque', text="1/k")
        self.industry15 = tk.Label(self, height=1, width=10, bg='bisque', text="1/k")
        self.industry16 = tk.Label(self, height=1, width=10, bg='bisque', text="1/k")
        self.industry17 = tk.Label(self, height=1, width=10, bg='bisque', text="1/k")
        self.industry18 = tk.Label(self, height=1, width=10, bg='bisque', text="1/k")
        self.industry19 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="1/k")
        self.industry20 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="1/k")
        self.industry21 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="1/k")
        self.industry22 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="1/k")
        self.industry23 = tk.Label(self, height=1, width=10, bg='bisque', text="1/k")
        self.industry24 = tk.Label(self, height=1, width=10, bg='bisque', text="1/k")
        self.industry25 = tk.Label(self, height=1, width=10, bg='bisque', text="1/k")
        self.industry26 = tk.Label(self, height=1, width=10, bg='bisque', text="1/k")

    # 期間細項
        self.period1 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="3/n")
        self.period2 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="3/n")
        self.period3 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="3/n")
        self.period4 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="3/n")
        self.period5 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="3/n")
        self.period6 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="3/n")
        self.period7 = tk.Label(self, height=1, width=10, bg='bisque', text="3/n")
        self.period8 = tk.Label(self, height=1, width=10, bg='bisque', text="3/n")
        self.period9 = tk.Label(self, height=1, width=10, bg='bisque', text="3/n")
        self.period10 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="3/n")
        self.period11 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="3/n")
        self.period12 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="3/n")
        self.period13 = tk.Label(self, height=1, width=10, bg='bisque', text="3/n")
        self.period14 = tk.Label(self, height=1, width=10, bg='bisque', text="3/n")
        self.period15 = tk.Label(self, height=1, width=10, bg='bisque', text="3/n")
        self.period16 = tk.Label(self, height=1, width=10, bg='bisque', text="3/n")
        self.period17 = tk.Label(self, height=1, width=10, bg='bisque', text="3/n")
        self.period18 = tk.Label(self, height=1, width=10, bg='bisque', text="3/n")
        self.period19 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="3/n")
        self.period20 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="3/n")
        self.period21 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="3/n")
        self.period22 = tk.Label(self, height=1, width=10, bg='LightSalmon', text="3/n")
        self.period23 = tk.Label(self, height=1, width=10, bg='bisque', text="3/n")
        self.period24 = tk.Label(self, height=1, width=10, bg='bisque', text="3/n")
        self.period25 = tk.Label(self, height=1, width=10, bg='bisque', text="3/n")
        self.period26 = tk.Label(self, height=1, width=10, bg='bisque', text="3/n")
        self.btn3 = tk.Button(self, height=3, width=10, text="Btn3", command= self.run_mainpage) # 觸發視窗