import tkinter as tk

class Window(tk.Frame):

    def __init__(self):
        tk.Frame.__init__(self)
        self.grid()
        self.create_widgets()

    def create_widgets(self):

        """Build Object/建立物件"""
    # 上方標題
        self.block_nmae = tk.Label(self, height=4, width=70, bg='skyblue', text="細項排名")
        self.item_name = tk.Label(self, height=2, width=10, bg='red', text="項目")
        self.index_name = tk.Label(self, height=2, width=40, bg='blue', text="指標名稱")
        self.industry = tk.Label(self, height=2, width=10, bg='red', text="產業")
        self.period = tk.Label(self, height=2, width=10, bg='blue', text="期間")

    # 左邊標題
        self.common_item = tk.Label(self, height=6, width=10, bg='lightsteelblue', text="常見\n指標")
        self.financial_structure = tk.Label(self, height=3, width=10, bg='lightsteelblue', text="財務\n結構")
        self.repay_capability = tk.Label(self, height=3, width=10, bg='lightsteelblue', text="償還\n能力")
        self.operate_capability = tk.Label(self, height=6, width=10, bg='lightsteelblue', text="經營\n能力")
        self.profit_capability = tk.Label(self, height=4, width=10, bg='lightsteelblue', text="獲利\n能力")
        self.cashflow = tk.Label(self, height=5, width=10, bg='lightsteelblue', text="現金\n流量")

    # 細項指標
        self.index1 = tk.Label(self, height=1, width=70, bg='green', text="淨利率")
        self.index2 = tk.Label(self, height=1, width=70, bg='green', text="毛利率")
        self.index3 = tk.Label(self, height=1, width=70, bg='green', text="殖利率")
        self.index4 = tk.Label(self, height=1, width=70, bg='green', text="股利發放穩定性")
        self.index5 = tk.Label(self, height=1, width=70, bg='green', text="盈餘分配率")
        self.index6 = tk.Label(self, height=1, width=70, bg='green', text="淨值比")
        self.index7 = tk.Label(self, height=1, width=70, bg='green', text="本益比")
        self.index8 = tk.Label(self, height=1, width=70, bg='green', text="負債占資產比率(%)")
        self.index9 = tk.Label(self, height=1, width=70, bg='green', text="長期資金站不動產廠房及設備比率(%)")
        self.index10 = tk.Label(self, height=1, width=70, bg='green', text="流動比率(%)")
        self.index11 = tk.Label(self, height=1, width=70, bg='green', text="速動比率(%)")
        self.index12 = tk.Label(self, height=1, width=70, bg='green', text="利息保障倍數(%)")
        self.index13 = tk.Label(self, height=1, width=70, bg='green', text="應收款項週轉率(次)")
        self.index14 = tk.Label(self, height=1, width=70, bg='green', text="平均收現日數")
        self.index15 = tk.Label(self, height=1, width=70, bg='green', text="存貨週轉率(次)")
        self.index16 = tk.Label(self, height=1, width=70, bg='green', text="平均銷貨日數")
        self.index17 = tk.Label(self, height=1, width=70, bg='green', text="不動產廠房及設備週轉率(次)")
        self.index18 = tk.Label(self, height=1, width=70, bg='green', text="總資產週轉率(次)")
        self.index19 = tk.Label(self, height=1, width=70, bg='green', text="資產報酬率(%)")
        self.index20 = tk.Label(self, height=1, width=70, bg='green', text="權益報酬率(%)")
        self.index21 = tk.Label(self, height=1, width=70, bg='green', text="稅前純益佔實收資本比率(%)")
        self.index22 = tk.Label(self, height=1, width=70, bg='green', text="純益率(%)")
        self.index23 = tk.Label(self, height=1, width=70, bg='green', text="每股盈餘(元)")
        self.index24 = tk.Label(self, height=1, width=70, bg='green', text="現金流量比率(%)")
        self.index25 = tk.Label(self, height=1, width=70, bg='green', text="現金流量允當比率(%)")
        self.index26 = tk.Label(self, height=1, width=70, bg='green', text="現金再投資比率(%)")

    # 產業細項
        self.industry1 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry2 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry3 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry4 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry5 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry6 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry7 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry8 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry9 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry10 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry11 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry12 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry13 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry14 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry15 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry16 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry17 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry18 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry19 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry20 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry21 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry22 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry23 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry24 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry25 = tk.Label(self, height=1, width=10, bg='green', text="1/k")
        self.industry26 = tk.Label(self, height=1, width=10, bg='green', text="1/k")

    # 期間細項
        self.period1 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period2 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period3 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period4 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period5 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period6 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period7 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period8 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period9 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period10 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period11 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period12 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period13 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period14 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period15 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period16 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period17 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period18 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period19 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period20 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period21 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period22 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period23 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period24 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period25 = tk.Label(self, height=1, width=10, bg='green', text="3/n")
        self.period26 = tk.Label(self, height=1, width=10, bg='green', text="3/n")


        """Assign Position/指定位置"""
    # 上方標題
        self.block_nmae.grid(row=0, column=0, columnspan=7, sticky=tk.SW + tk.NE)
        self.item_name.grid(row=1, column=0,sticky=tk.W)
        self.index_name.grid(row=1, column=1, columnspan=4, sticky=tk.SW + tk. NE)
        self.industry.grid(row=1, column=5,sticky=tk.W)
        self.period.grid(row=1, column=6,sticky=tk.W)

    # 左邊標題
        self.common_item.grid(row=4,column=0,rowspan=7,sticky=tk.NE +tk.SW)
        self.financial_structure.grid(row=10, column=0, rowspan=3, sticky=tk.NE +tk.SW)
        self.repay_capability.grid(row=13, column=0, rowspan=3, sticky=tk.NE +tk.SW)
        self.operate_capability.grid(row=16, column=0, rowspan=6, sticky=tk.NE +tk.SW)
        self.profit_capability.grid(row=22, column=0, rowspan=4, sticky=tk.NE +tk.SW)
        self.cashflow.grid(row=26, column=0, rowspan=5, sticky=tk.NE +tk.SW)

    #細項指標
        self.index1.grid(row=4, column=1, columnspan=4, sticky=tk.W)
        self.index2.grid(row=5, column=1, columnspan=4, sticky=tk.W)
        self.index3.grid(row=6, column=1, columnspan=4, sticky=tk.W)
        self.index4.grid(row=7, column=1, columnspan=4, sticky=tk.W)
        self.index5.grid(row=8, column=1, columnspan=4, sticky=tk.W)
        self.index6.grid(row=9, column=1, columnspan=4, sticky=tk.W)
        self.index7.grid(row=10, column=1, columnspan=4, sticky=tk.W)
        self.index8.grid(row=11, column=1, columnspan=4, sticky=tk.W)
        self.index9.grid(row=12, column=1, columnspan=4, sticky=tk.W)
        self.index10.grid(row=13, column=1, columnspan=4, sticky=tk.W)
        self.index11.grid(row=14, column=1, columnspan=4, sticky=tk.W)
        self.index12.grid(row=15, column=1, columnspan=4, sticky=tk.W)
        self.index13.grid(row=16, column=1, columnspan=4, sticky=tk.W)
        self.index14.grid(row=17, column=1, columnspan=4, sticky=tk.W)
        self.index15.grid(row=18, column=1, columnspan=4, sticky=tk.W)
        self.index16.grid(row=19, column=1, columnspan=4, sticky=tk.W)
        self.index17.grid(row=20, column=1, columnspan=4, sticky=tk.W)
        self.index18.grid(row=21, column=1, columnspan=4, sticky=tk.W)
        self.index19.grid(row=22, column=1, columnspan=4, sticky=tk.W)
        self.index20.grid(row=23, column=1, columnspan=4, sticky=tk.W)
        self.index21.grid(row=24, column=1, columnspan=4, sticky=tk.W)
        self.index22.grid(row=25, column=1, columnspan=4, sticky=tk.W)
        self.index23.grid(row=26, column=1, columnspan=4, sticky=tk.W)
        self.index24.grid(row=27, column=1, columnspan=4, sticky=tk.W)
        self.index25.grid(row=28, column=1, columnspan=4, sticky=tk.W)
        self.index26.grid(row=29, column=1, columnspan=4, sticky=tk.W)

    #產業細項
        self.industry1.grid(row=4, column=5, sticky=tk.W)
        self.industry2.grid(row=5, column=5, sticky=tk.W)
        self.industry3.grid(row=6, column=5, sticky=tk.W)
        self.industry4.grid(row=7, column=5, sticky=tk.W)
        self.industry5.grid(row=8, column=5, sticky=tk.W)
        self.industry6.grid(row=9, column=5, sticky=tk.W)
        self.industry7.grid(row=10, column=5, sticky=tk.W)
        self.industry8.grid(row=11, column=5, sticky=tk.W)
        self.industry9.grid(row=12, column=5, sticky=tk.W)
        self.industry10.grid(row=13, column=5, sticky=tk.W)
        self.industry11.grid(row=14, column=5, sticky=tk.W)
        self.industry12.grid(row=15, column=5, sticky=tk.W)
        self.industry13.grid(row=16, column=5, sticky=tk.W)
        self.industry14.grid(row=17, column=5, sticky=tk.W)
        self.industry15.grid(row=18, column=5, sticky=tk.W)
        self.industry16.grid(row=19, column=5, sticky=tk.W)
        self.industry17.grid(row=20, column=5, sticky=tk.W)
        self.industry18.grid(row=21, column=5, sticky=tk.W)
        self.industry19.grid(row=22, column=5, sticky=tk.W)
        self.industry20.grid(row=23, column=5, sticky=tk.W)
        self.industry21.grid(row=24, column=5, sticky=tk.W)
        self.industry22.grid(row=25, column=5, sticky=tk.W)
        self.industry23.grid(row=26, column=5, sticky=tk.W)
        self.industry24.grid(row=27, column=5, sticky=tk.W)
        self.industry25.grid(row=28, column=5, sticky=tk.W)
        self.industry26.grid(row=29, column=5, sticky=tk.W)

    #期間細項
        self.period1.grid(row=4, column=6, sticky=tk.W)
        self.period2.grid(row=5, column=6, sticky=tk.W)
        self.period3.grid(row=6, column=6, sticky=tk.W)
        self.period4.grid(row=7, column=6, sticky=tk.W)
        self.period5.grid(row=8, column=6, sticky=tk.W)
        self.period6.grid(row=9, column=6, sticky=tk.W)
        self.period7.grid(row=10, column=6, sticky=tk.W)
        self.period8.grid(row=11, column=6, sticky=tk.W)
        self.period9.grid(row=12, column=6, sticky=tk.W)
        self.period10.grid(row=13, column=6, sticky=tk.W)
        self.period11.grid(row=14, column=6, sticky=tk.W)
        self.period12.grid(row=15, column=6, sticky=tk.W)
        self.period13.grid(row=16, column=6, sticky=tk.W)
        self.period14.grid(row=17, column=6, sticky=tk.W)
        self.period15.grid(row=18, column=6, sticky=tk.W)
        self.period16.grid(row=19, column=6, sticky=tk.W)
        self.period17.grid(row=20, column=6, sticky=tk.W)
        self.period18.grid(row=21, column=6, sticky=tk.W)
        self.period19.grid(row=22, column=6, sticky=tk.W)
        self.period20.grid(row=23, column=6, sticky=tk.W)
        self.period21.grid(row=24, column=6, sticky=tk.W)
        self.period22.grid(row=25, column=6, sticky=tk.W)
        self.period23.grid(row=26, column=6, sticky=tk.W)
        self.period24.grid(row=27, column=6, sticky=tk.W)
        self.period25.grid(row=28, column=6, sticky=tk.W)
        self.period26.grid(row=29, column=6, sticky=tk.W)


mywindow = Window()
mywindow.master.title("my window")
mywindow.mainloop()